[package]
name = "human-panic"
version = "0.2.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/human-panic"
homepage = "https://github.com/yoshuawuyts/human-panic"
documentation = "https://docs.rs/human-panic"
description = "Panic messages for humans"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
readme = "README.md"

[dependencies]
unindent = "0.1.2"
failure = "0.1.1"
console = "0.6.1"

[dev-dependencies]
clippy = "0.0"
